paths:
  data: data
  collections: content
  includes: layouts
  layouts: layouts
  static: static
  uploads: static/uploads
  source: ''
  archetypes: archetypes
  assets: assets
  content: content
  pages: content
  publish: public
  config: ''
collections_config:
  pages:
    path: content
    output: true
    filter: strict
    parse_branch_index: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  music:
    path: content/music
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  projects:
    path: content/projects
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  words:
    path: content/words
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  data:
    path: data
    output: false
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
timezone: Etc/UTC
